# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_SpeechSynthesizerForm.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SpeechSynthesizerForm(object):
    def setupUi(self, SpeechSynthesizerForm):
        SpeechSynthesizerForm.setObjectName("SpeechSynthesizerForm")
        SpeechSynthesizerForm.resize(530, 674)
        self.le_text = QtWidgets.QLineEdit(SpeechSynthesizerForm)
        self.le_text.setGeometry(QtCore.QRect(10, 50, 511, 20))
        self.le_text.setObjectName("le_text")
        self.pb_add_syllable = QtWidgets.QPushButton(SpeechSynthesizerForm)
        self.pb_add_syllable.setGeometry(QtCore.QRect(60, 240, 421, 41))
        self.pb_add_syllable.setObjectName("pb_add_syllable")
        self.pb_play = QtWidgets.QPushButton(SpeechSynthesizerForm)
        self.pb_play.setEnabled(False)
        self.pb_play.setGeometry(QtCore.QRect(10, 610, 511, 51))
        self.pb_play.setObjectName("pb_play")
        self.lbl_text = QtWidgets.QLabel(SpeechSynthesizerForm)
        self.lbl_text.setGeometry(QtCore.QRect(150, 20, 251, 16))
        self.lbl_text.setObjectName("lbl_text")
        self.lbl_image = QtWidgets.QLabel(SpeechSynthesizerForm)
        self.lbl_image.setGeometry(QtCore.QRect(10, 320, 501, 251))
        self.lbl_image.setText("")
        self.lbl_image.setObjectName("lbl_image")
        self.gridLayoutWidget = QtWidgets.QWidget(SpeechSynthesizerForm)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 110, 511, 112))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pb_r = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_r.setObjectName("pb_r")
        self.gridLayout.addWidget(self.pb_r, 2, 5, 1, 1)
        self.pb_shch = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_shch.setObjectName("pb_shch")
        self.gridLayout.addWidget(self.pb_shch, 1, 8, 1, 1)
        self.pb_u = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_u.setObjectName("pb_u")
        self.gridLayout.addWidget(self.pb_u, 1, 2, 1, 1)
        self.pb_ye2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_ye2.setObjectName("pb_ye2")
        self.gridLayout.addWidget(self.pb_ye2, 2, 11, 1, 1)
        self.pb_sg = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_sg.setObjectName("pb_sg")
        self.gridLayout.addWidget(self.pb_sg, 3, 7, 1, 1)
        self.pb_z = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_z.setObjectName("pb_z")
        self.gridLayout.addWidget(self.pb_z, 1, 9, 1, 1)
        self.pb_n = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_n.setObjectName("pb_n")
        self.gridLayout.addWidget(self.pb_n, 1, 5, 1, 1)
        self.pb_hs = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_hs.setObjectName("pb_hs")
        self.gridLayout.addWidget(self.pb_hs, 1, 11, 1, 1)
        self.pb_k = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_k.setObjectName("pb_k")
        self.gridLayout.addWidget(self.pb_k, 1, 3, 1, 1)
        self.pb_f = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_f.setObjectName("pb_f")
        self.gridLayout.addWidget(self.pb_f, 2, 0, 1, 1)
        self.pb_t = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_t.setObjectName("pb_t")
        self.gridLayout.addWidget(self.pb_t, 3, 6, 1, 1)
        self.pb_l = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_l.setObjectName("pb_l")
        self.gridLayout.addWidget(self.pb_l, 2, 7, 1, 1)
        self.pb_e = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_e.setObjectName("pb_e")
        self.gridLayout.addWidget(self.pb_e, 2, 10, 1, 1)
        self.pb_zh = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_zh.setObjectName("pb_zh")
        self.gridLayout.addWidget(self.pb_zh, 2, 9, 1, 1)
        self.pb_ye = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_ye.setObjectName("pb_ye")
        self.gridLayout.addWidget(self.pb_ye, 1, 4, 1, 1)
        self.pb_b = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_b.setObjectName("pb_b")
        self.gridLayout.addWidget(self.pb_b, 3, 8, 1, 1)
        self.pb_p = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_p.setObjectName("pb_p")
        self.gridLayout.addWidget(self.pb_p, 2, 4, 1, 1)
        self.pb_g = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_g.setObjectName("pb_g")
        self.gridLayout.addWidget(self.pb_g, 1, 6, 1, 1)
        self.pb_m = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_m.setObjectName("pb_m")
        self.gridLayout.addWidget(self.pb_m, 3, 4, 1, 1)
        self.pb_o = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_o.setObjectName("pb_o")
        self.gridLayout.addWidget(self.pb_o, 2, 6, 1, 1)
        self.pb_j = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_j.setObjectName("pb_j")
        self.gridLayout.addWidget(self.pb_j, 1, 0, 1, 1)
        self.pb_yu = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_yu.setObjectName("pb_yu")
        self.gridLayout.addWidget(self.pb_yu, 3, 9, 1, 1)
        self.pb_i = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_i.setObjectName("pb_i")
        self.gridLayout.addWidget(self.pb_i, 3, 5, 1, 1)
        self.pb_s = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_s.setObjectName("pb_s")
        self.gridLayout.addWidget(self.pb_s, 3, 3, 1, 1)
        self.pb_sh = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_sh.setObjectName("pb_sh")
        self.gridLayout.addWidget(self.pb_sh, 1, 7, 1, 1)
        self.pb_d = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_d.setObjectName("pb_d")
        self.gridLayout.addWidget(self.pb_d, 2, 8, 1, 1)
        self.pb_y = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_y.setObjectName("pb_y")
        self.gridLayout.addWidget(self.pb_y, 2, 1, 1, 1)
        self.pb_ts = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_ts.setObjectName("pb_ts")
        self.gridLayout.addWidget(self.pb_ts, 1, 1, 1, 1)
        self.pb_a = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_a.setObjectName("pb_a")
        self.gridLayout.addWidget(self.pb_a, 2, 3, 1, 1)
        self.pb_v = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_v.setObjectName("pb_v")
        self.gridLayout.addWidget(self.pb_v, 2, 2, 1, 1)
        self.pb_kh = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_kh.setObjectName("pb_kh")
        self.gridLayout.addWidget(self.pb_kh, 1, 10, 1, 1)
        self.pb_ch = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_ch.setObjectName("pb_ch")
        self.gridLayout.addWidget(self.pb_ch, 3, 2, 1, 1)
        self.pb_ya = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_ya.setObjectName("pb_ya")
        self.gridLayout.addWidget(self.pb_ya, 3, 1, 1, 1)
        self.pb_delete_all = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pb_delete_all.setObjectName("pb_delete_all")
        self.gridLayout.addWidget(self.pb_delete_all, 3, 10, 1, 2)
        self.pb_delete_one_letter = QtWidgets.QPushButton(SpeechSynthesizerForm)
        self.pb_delete_one_letter.setGeometry(QtCore.QRect(400, 80, 121, 23))
        self.pb_delete_one_letter.setObjectName("pb_delete_one_letter")
        self.checkBox = QtWidgets.QCheckBox(SpeechSynthesizerForm)
        self.checkBox.setGeometry(QtCore.QRect(20, 80, 201, 21))
        self.checkBox.setObjectName("checkBox")
        self.comboBox = QtWidgets.QComboBox(SpeechSynthesizerForm)
        self.comboBox.setGeometry(QtCore.QRect(438, 20, 81, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pb_bd = QtWidgets.QPushButton(SpeechSynthesizerForm)
        self.pb_bd.setGeometry(QtCore.QRect(20, 10, 41, 31))
        self.pb_bd.setObjectName("pb_bd")

        self.retranslateUi(SpeechSynthesizerForm)
        QtCore.QMetaObject.connectSlotsByName(SpeechSynthesizerForm)

    def retranslateUi(self, SpeechSynthesizerForm):
        _translate = QtCore.QCoreApplication.translate
        SpeechSynthesizerForm.setWindowTitle(_translate("SpeechSynthesizerForm", "Синтез речи"))
        self.pb_add_syllable.setText(
            _translate("SpeechSynthesizerForm", "Записать и добавить слог или букву в базу данных(F2)"))
        self.pb_play.setText(_translate("SpeechSynthesizerForm", "Воспроизвести(F1)"))
        self.lbl_text.setText(_translate("SpeechSynthesizerForm", "Введите текст, который хотите воспроизвести"))
        self.pb_r.setText(_translate("SpeechSynthesizerForm", "р"))
        self.pb_shch.setText(_translate("SpeechSynthesizerForm", "щ"))
        self.pb_u.setText(_translate("SpeechSynthesizerForm", "у"))
        self.pb_ye2.setText(_translate("SpeechSynthesizerForm", "ё"))
        self.pb_sg.setText(_translate("SpeechSynthesizerForm", "ь"))
        self.pb_z.setText(_translate("SpeechSynthesizerForm", "з"))
        self.pb_n.setText(_translate("SpeechSynthesizerForm", "н"))
        self.pb_hs.setText(_translate("SpeechSynthesizerForm", "ъ"))
        self.pb_k.setText(_translate("SpeechSynthesizerForm", "к"))
        self.pb_f.setText(_translate("SpeechSynthesizerForm", "ф"))
        self.pb_t.setText(_translate("SpeechSynthesizerForm", "т"))
        self.pb_l.setText(_translate("SpeechSynthesizerForm", "л"))
        self.pb_e.setText(_translate("SpeechSynthesizerForm", "э"))
        self.pb_zh.setText(_translate("SpeechSynthesizerForm", "ж"))
        self.pb_ye.setText(_translate("SpeechSynthesizerForm", "е"))
        self.pb_b.setText(_translate("SpeechSynthesizerForm", "б"))
        self.pb_p.setText(_translate("SpeechSynthesizerForm", "п"))
        self.pb_g.setText(_translate("SpeechSynthesizerForm", "г"))
        self.pb_m.setText(_translate("SpeechSynthesizerForm", "м"))
        self.pb_o.setText(_translate("SpeechSynthesizerForm", "о"))
        self.pb_j.setText(_translate("SpeechSynthesizerForm", "й"))
        self.pb_yu.setText(_translate("SpeechSynthesizerForm", "ю"))
        self.pb_i.setText(_translate("SpeechSynthesizerForm", "и"))
        self.pb_s.setText(_translate("SpeechSynthesizerForm", "с"))
        self.pb_sh.setText(_translate("SpeechSynthesizerForm", "ш"))
        self.pb_d.setText(_translate("SpeechSynthesizerForm", "д"))
        self.pb_y.setText(_translate("SpeechSynthesizerForm", "ы"))
        self.pb_ts.setText(_translate("SpeechSynthesizerForm", "ц"))
        self.pb_a.setText(_translate("SpeechSynthesizerForm", "а"))
        self.pb_v.setText(_translate("SpeechSynthesizerForm", "в"))
        self.pb_kh.setText(_translate("SpeechSynthesizerForm", "х"))
        self.pb_ch.setText(_translate("SpeechSynthesizerForm", "ч"))
        self.pb_ya.setText(_translate("SpeechSynthesizerForm", "я"))
        self.pb_delete_all.setText(_translate("SpeechSynthesizerForm", "Удалить всё"))
        self.pb_delete_one_letter.setText(_translate("SpeechSynthesizerForm", "Удалить одну букву"))
        self.checkBox.setText(_translate("SpeechSynthesizerForm", "Синтез речи в реальном времени"))
        self.comboBox.setItemText(0, _translate("SpeechSynthesizerForm", "Denis TTS"))
        self.comboBox.setItemText(1, _translate("SpeechSynthesizerForm", "Google TTS"))
        self.pb_bd.setText(_translate("SpeechSynthesizerForm", "БД"))
